//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategoryTable
    {
        public SubCategoryTable()
        {
            this.ProductTables = new HashSet<ProductTable>();
        }
    
        public int SubCategoryId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string SubCategoryName { get; set; }
        public string Description { get; set; }
    
        public virtual CategoryTable CategoryTable { get; set; }
        public virtual ICollection<ProductTable> ProductTables { get; set; }
    }
}
