//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTable
    {
        public int SalesId { get; set; }
        public Nullable<int> SalesCodeId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<double> SalesQuantity { get; set; }
    }
}
