//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesCodeTable
    {
        public SalesCodeTable()
        {
            this.BillTables = new HashSet<BillTable>();
            this.SalesTables = new HashSet<SalesTable>();
        }
    
        public int SalesCodeId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> SalesDate { get; set; }
        public string CustomerEmail { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<BillTable> BillTables { get; set; }
        public virtual ICollection<SalesTable> SalesTables { get; set; }
    }
}
